### PR TITLE
Bump HAL to upcomming release

### PR DESCRIPTION
**Pull request by sirhcel**
Thank you for your [feedback](https://github.com/sirhcel/stm32f3-discovery/commit/ef58a2a2b81a6efae483090b0ed220e9b7b76396#commitcomment-52243848) @rubberduck203! I will take it as an encouragement to surface my current WIP for switching to the upcoming release of the HAL for https://github.com/rust-embedded/discovery/pull/267.

It builds on the current _master_ plus ongoing UART refactoring. I will update this WIP until the HAL release lands.

### CODE REVIEW

**Comment by rubberduck203** [comment]
Thanks!
I’m just happy someone found this useful enough to hack on it themselves. 
This will save me a fair bit of work, so I really appreciate it.

**Comment by sirhcel** [comment]
Thank you for caring for this BSP! Now, the day has come and `stm32f3xx-hal` 0.7.0 got released and this PR is ready to roll.

I'd like to have a look at https://github.com/rubberduck203/stm32f3-discovery/issues/7 this weekend. As this PR brings breaking changes, adding support for the gyroscope as well looks like a low-hanging fruit at the moment to me.

I could prepare bumping the minor version of this crate and release notes, if you like.

**Comment by rubberduck203** [comment]
That would be nice. Thank you.

**Comment by rubberduck203** [comment]
Tests are green, so I’m going to sit down and get this released later today.

**Comment by sirhcel** [comment]
Thank you very much for creating the new release! :) This also buys time for our discussion of the issues.

**Pull request merged**
