### PR TITLE
Accelerometer & Led PWM demo

### PR DESCRIPTION
**Pull request by sim82**
Hi, I've created an example that uses the accelerometer to modulate the brightness of thee LEDs via PWM (using a LUT to get a nice linear brightness change). In a nutshell this is the demo I've been looking for when I first started using the discovery board and I think it would be a nice addition...

### CODE REVIEW

**Comment by rubberduck203** [comment]
This is awesome! I’m very much looking forward to testing this this weekend!

**Comment by rubberduck203** [comment]
Sorry it took me so long to get around to looking at this.
This seems to work okay, but the axis seem off when I run the code.
Laying flat, `LD4` (blue) is always on.
The green and red lights also sometimes act in surprising ways.

What should the behavior be?

I mean, it's a great start regardless and I'm likely to merge this as is, but if you can describe how it should behave, I'm better equipped to improve it.

**Comment by sim82** [comment]
Hi, so the three LEDs should gradually light up corresponding to the orientation of the board along its three axes (or more precisely they indicate the direction of Earth's gravity relative to the three axes of the board):

- lying down flat the blue LDE should be full on, indicating that gravity is perpendicular to the board.
- when you slowly turn it around its long axis the green LED should gradually go on while the blue gradually fades out. The green LED should be fully on when the green LED is 'facing down' and the other axes are straight.
- likewise when you turn it along the short axis (from a flat position) the red LED will go on.

I hope your board acts roughly the same, i.e. that the accelerometers are more or less calibrated the same on all boards. Also there might be some flickering when it is moved quickly or when the LEDs are very dim due to noise in the sensor signal. Filtering the sensor signal and/or adding some calibration method might be a future improvement.

**Comment by rubberduck203** [comment]
I was finally able to confirm that is exactly the behavior I was seeing.
It just wasn't the behavior I had preconceived when I thought about adding this example myself.
I'm going to merge it and add a few comments from your reply.

Thank you very much for this!

**Pull request merged**
